### ISSUE TITLE
/Users/anthonyyuan/torch/install/bin/luajit: ...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ...earning-master/pixelInterpolation/data/donkey_folder.lua:24: bad argument #2 to 'error' (number expected, got string) stack traceback:

### ISSUE THREAD

**Issue by anthonyyuan** [rhgao/on-demand-learning#1]
DATA_ROOT=../dataset/my_test_set name=pixelInter_demo net=../models/pixelInterpolation_net_G.t7 manualSeed=333 gpu=1 display=1 th demo.lua
{
  gpu : 1
  nc : 3
  name : "pixelInter_demo"
  batchSize : 100
  net : "../models/pixelInterpolation_net_G.t7"
  fineSize : 64
  manualSeed : 333
  nThreads : 1
  display : 1
  loadSize : 96
}
Seed: 333	
Using CUDNN !	
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> output]
  (1): nn.Sequential {
    [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> output]
    (1): cudnn.SpatialConvolution(3 -> 64, 4x4, 2,2, 1,1)
    (2): nn.SpatialBatchNormalization (4D) (64)
    (3): nn.LeakyReLU(0.2)
    (4): cudnn.SpatialConvolution(64 -> 128, 4x4, 2,2, 1,1)
    (5): nn.SpatialBatchNormalization (4D) (128)
    (6): nn.LeakyReLU(0.2)
    (7): cudnn.SpatialConvolution(128 -> 256, 4x4, 2,2, 1,1)
    (8): nn.SpatialBatchNormalization (4D) (256)
    (9): nn.LeakyReLU(0.2)
    (10): cudnn.SpatialConvolution(256 -> 512, 4x4, 2,2, 1,1)
    (11): nn.SpatialBatchNormalization (4D) (512)
    (12): nn.LeakyReLU(0.2)
  }
  (2): nn.Sequential {
    [input -> (1) -> (2) -> (3) -> (4) -> output]
    (1): nn.View(512, 16)
    (2): nn.SplitTable
    (3): nn.ParallelTable {
      input
        |`-> (1): nn.Linear(16 -> 16)
        |`-> (2): nn.Linear(16 -> 16)
        |`-> (3): nn.Linear(16 -> 16)
        |`-> (4): nn.Linear(16 -> 16)
        |`-> (5): nn.Linear(16 -> 16)
        |`-> (6): nn.Linear(16 -> 16)
        |`-> (7): nn.Linear(16 -> 16)
        |`-> (8): nn.Linear(16 -> 16)
        |`-> (9): nn.Linear(16 -> 16)
        |`-> (10): nn.Linear(16 -> 16)
        |`-> (11): nn.Linear(16 -> 16)
        |`-> (12): nn.Linear(16 -> 16)
        |`-> (13): nn.Linear(16 -> 16)
        |`-> (14): nn.Linear(16 -> 16)
        |`-> (15): nn.Linear(16 -> 16)
        |`-> (16): nn.Linear(16 -> 16)
        |`-> (17): nn.Linear(16 -> 16)
        |`-> (18): nn.Linear(16 -> 16)
        |`-> (19): nn.Linear(16 -> 16)
        |`-> (20): nn.Linear(16 -> 16)
        |`-> (21): nn.Linear(16 -> 16)
        |`-> (22): nn.Linear(16 -> 16)
        |`-> (23): nn.Linear(16 -> 16)
        |`-> (24): nn.Linear(16 -> 16)
        |`-> (25): nn.Linear(16 -> 16)
        |`-> (26): nn.Linear(16 -> 16)
        |`-> (27): nn.Linear(16 -> 16)
        |`-> (28): nn.Linear(16 -> 16)
        |`-> (29): nn.Linear(16 -> 16)
        |`-> (30): nn.Linear(16 -> 16)
        |`-> (31): nn.Linear(16 -> 16)
        |`-> (32): nn.Linear(16 -> 16)
        |`-> (33): nn.Linear(16 -> 16)
        |`-> (34): nn.Linear(16 -> 16)
        |`-> (35): nn.Linear(16 -> 16)
        |`-> (36): nn.Linear(16 -> 16)
        |`-> (37): nn.Linear(16 -> 16)
        |`-> (38): nn.Linear(16 -> 16)
        |`-> (39): nn.Linear(16 -> 16)
        |`-> (40): nn.Linear(16 -> 16)
        |`-> (41): nn.Linear(16 -> 16)
        |`-> (42): nn.Linear(16 -> 16)
        |`-> (43): nn.Linear(16 -> 16)
        |`-> (44): nn.Linear(16 -> 16)
        |`-> (45): nn.Linear(16 -> 16)
        |`-> (46): nn.Linear(16 -> 16)
        |`-> (47): nn.Linear(16 -> 16)
        |`-> (48): nn.Linear(16 -> 16)
        |`-> (49): nn.Linear(16 -> 16)
        |`-> (50): nn.Linear(16 -> 16)
        |`-> (51): nn.Linear(16 -> 16)
        |`-> (52): nn.Linear(16 -> 16)
        |`-> (53): nn.Linear(16 -> 16)
        |`-> (54): nn.Linear(16 -> 16)
        |`-> (55): nn.Linear(16 -> 16)
        |`-> (56): nn.Linear(16 -> 16)
        |`-> (57): nn.Linear(16 -> 16)
        |`-> (58): nn.Linear(16 -> 16)
        |`-> (59): nn.Linear(16 -> 16)
        |`-> (60): nn.Linear(16 -> 16)
        |`-> (61): nn.Linear(16 -> 16)
        |`-> (62): nn.Linear(16 -> 16)
        |`-> (63): nn.Linear(16 -> 16)
        |`-> (64): nn.Linear(16 -> 16)
        |`-> (65): nn.Linear(16 -> 16)
        |`-> (66): nn.Linear(16 -> 16)
        |`-> (67): nn.Linear(16 -> 16)
        |`-> (68): nn.Linear(16 -> 16)
        |`-> (69): nn.Linear(16 -> 16)
        |`-> (70): nn.Linear(16 -> 16)
        |`-> (71): nn.Linear(16 -> 16)
        |`-> (72): nn.Linear(16 -> 16)
        |`-> (73): nn.Linear(16 -> 16)
        |`-> (74): nn.Linear(16 -> 16)
        |`-> (75): nn.Linear(16 -> 16)
        |`-> (76): nn.Linear(16 -> 16)
        |`-> (77): nn.Linear(16 -> 16)
        |`-> (78): nn.Linear(16 -> 16)
        |`-> (79): nn.Linear(16 -> 16)
        |`-> (80): nn.Linear(16 -> 16)
        |`-> (81): nn.Linear(16 -> 16)
        |`-> (82): nn.Linear(16 -> 16)
        |`-> (83): nn.Linear(16 -> 16)
        |`-> (84): nn.Linear(16 -> 16)
        |`-> (85): nn.Linear(16 -> 16)
        |`-> (86): nn.Linear(16 -> 16)
        |`-> (87): nn.Linear(16 -> 16)
        |`-> (88): nn.Linear(16 -> 16)
        |`-> (89): nn.Linear(16 -> 16)
        |`-> (90): nn.Linear(16 -> 16)
        |`-> (91): nn.Linear(16 -> 16)
        |`-> (92): nn.Linear(16 -> 16)
        |`-> (93): nn.Linear(16 -> 16)
        |`-> (94): nn.Linear(16 -> 16)
        |`-> (95): nn.Linear(16 -> 16)
        |`-> (96): nn.Linear(16 -> 16)
        |`-> (97): nn.Linear(16 -> 16)
        |`-> (98): nn.Linear(16 -> 16)
        |`-> (99): nn.Linear(16 -> 16)
        |`-> (100): nn.Linear(16 -> 16)
        |`-> (101): nn.Linear(16 -> 16)
        |`-> (102): nn.Linear(16 -> 16)
        |`-> (103): nn.Linear(16 -> 16)
        |`-> (104): nn.Linear(16 -> 16)
        |`-> (105): nn.Linear(16 -> 16)
        |`-> (106): nn.Linear(16 -> 16)
        |`-> (107): nn.Linear(16 -> 16)
        |`-> (108): nn.Linear(16 -> 16)
        |`-> (109): nn.Linear(16 -> 16)
        |`-> (110): nn.Linear(16 -> 16)
        |`-> (111): nn.Linear(16 -> 16)
        |`-> (112): nn.Linear(16 -> 16)
        |`-> (113): nn.Linear(16 -> 16)
        |`-> (114): nn.Linear(16 -> 16)
        |`-> (115): nn.Linear(16 -> 16)
        |`-> (116): nn.Linear(16 -> 16)
        |`-> (117): nn.Linear(16 -> 16)
        |`-> (118): nn.Linear(16 -> 16)
        |`-> (119): nn.Linear(16 -> 16)
        |`-> (120): nn.Linear(16 -> 16)
        |`-> (121): nn.Linear(16 -> 16)
        |`-> (122): nn.Linear(16 -> 16)
        |`-> (123): nn.Linear(16 -> 16)
        |`-> (124): nn.Linear(16 -> 16)
        |`-> (125): nn.Linear(16 -> 16)
        |`-> (126): nn.Linear(16 -> 16)
        |`-> (127): nn.Linear(16 -> 16)
        |`-> (128): nn.Linear(16 -> 16)
        |`-> (129): nn.Linear(16 -> 16)
        |`-> (130): nn.Linear(16 -> 16)
        |`-> (131): nn.Linear(16 -> 16)
        |`-> (132): nn.Linear(16 -> 16)
        |`-> (133): nn.Linear(16 -> 16)
        |`-> (134): nn.Linear(16 -> 16)
        |`-> (135): nn.Linear(16 -> 16)
        |`-> (136): nn.Linear(16 -> 16)
        |`-> (137): nn.Linear(16 -> 16)
        |`-> (138): nn.Linear(16 -> 16)
        |`-> (139): nn.Linear(16 -> 16)
        |`-> (140): nn.Linear(16 -> 16)
        |`-> (141): nn.Linear(16 -> 16)
        |`-> (142): nn.Linear(16 -> 16)
        |`-> (143): nn.Linear(16 -> 16)
        |`-> (144): nn.Linear(16 -> 16)
        |`-> (145): nn.Linear(16 -> 16)
        |`-> (146): nn.Linear(16 -> 16)
        |`-> (147): nn.Linear(16 -> 16)
        |`-> (148): nn.Linear(16 -> 16)
        |`-> (149): nn.Linear(16 -> 16)
        |`-> (150): nn.Linear(16 -> 16)
        |`-> (151): nn.Linear(16 -> 16)
        |`-> (152): nn.Linear(16 -> 16)
        |`-> (153): nn.Linear(16 -> 16)
        |`-> (154): nn.Linear(16 -> 16)
        |`-> (155): nn.Linear(16 -> 16)
        |`-> (156): nn.Linear(16 -> 16)
        |`-> (157): nn.Linear(16 -> 16)
        |`-> (158): nn.Linear(16 -> 16)
        |`-> (159): nn.Linear(16 -> 16)
        |`-> (160): nn.Linear(16 -> 16)
        |`-> (161): nn.Linear(16 -> 16)
        |`-> (162): nn.Linear(16 -> 16)
        |`-> (163): nn.Linear(16 -> 16)
        |`-> (164): nn.Linear(16 -> 16)
        |`-> (165): nn.Linear(16 -> 16)
        |`-> (166): nn.Linear(16 -> 16)
        |`-> (167): nn.Linear(16 -> 16)
        |`-> (168): nn.Linear(16 -> 16)
        |`-> (169): nn.Linear(16 -> 16)
        |`-> (170): nn.Linear(16 -> 16)
        |`-> (171): nn.Linear(16 -> 16)
        |`-> (172): nn.Linear(16 -> 16)
        |`-> (173): nn.Linear(16 -> 16)
        |`-> (174): nn.Linear(16 -> 16)
        |`-> (175): nn.Linear(16 -> 16)
        |`-> (176): nn.Linear(16 -> 16)
        |`-> (177): nn.Linear(16 -> 16)
        |`-> (178): nn.Linear(16 -> 16)
        |`-> (179): nn.Linear(16 -> 16)
        |`-> (180): nn.Linear(16 -> 16)
        |`-> (181): nn.Linear(16 -> 16)
        |`-> (182): nn.Linear(16 -> 16)
        |`-> (183): nn.Linear(16 -> 16)
        |`-> (184): nn.Linear(16 -> 16)
        |`-> (185): nn.Linear(16 -> 16)
        |`-> (186): nn.Linear(16 -> 16)
        |`-> (187): nn.Linear(16 -> 16)
        |`-> (188): nn.Linear(16 -> 16)
        |`-> (189): nn.Linear(16 -> 16)
        |`-> (190): nn.Linear(16 -> 16)
        |`-> (191): nn.Linear(16 -> 16)
        |`-> (192): nn.Linear(16 -> 16)
        |`-> (193): nn.Linear(16 -> 16)
        |`-> (194): nn.Linear(16 -> 16)
        |`-> (195): nn.Linear(16 -> 16)
        |`-> (196): nn.Linear(16 -> 16)
        |`-> (197): nn.Linear(16 -> 16)
        |`-> (198): nn.Linear(16 -> 16)
        |`-> (199): nn.Linear(16 -> 16)
        |`-> (200): nn.Linear(16 -> 16)
        |`-> (201): nn.Linear(16 -> 16)
        |`-> (202): nn.Linear(16 -> 16)
        |`-> (203): nn.Linear(16 -> 16)
        |`-> (204): nn.Linear(16 -> 16)
        |`-> (205): nn.Linear(16 -> 16)
        |`-> (206): nn.Linear(16 -> 16)
        |`-> (207): nn.Linear(16 -> 16)
        |`-> (208): nn.Linear(16 -> 16)
        |`-> (209): nn.Linear(16 -> 16)
        |`-> (210): nn.Linear(16 -> 16)
        |`-> (211): nn.Linear(16 -> 16)
        |`-> (212): nn.Linear(16 -> 16)
        |`-> (213): nn.Linear(16 -> 16)
        |`-> (214): nn.Linear(16 -> 16)
        |`-> (215): nn.Linear(16 -> 16)
        |`-> (216): nn.Linear(16 -> 16)
        |`-> (217): nn.Linear(16 -> 16)
        |`-> (218): nn.Linear(16 -> 16)
        |`-> (219): nn.Linear(16 -> 16)
        |`-> (220): nn.Linear(16 -> 16)
        |`-> (221): nn.Linear(16 -> 16)
        |`-> (222): nn.Linear(16 -> 16)
        |`-> (223): nn.Linear(16 -> 16)
        |`-> (224): nn.Linear(16 -> 16)
        |`-> (225): nn.Linear(16 -> 16)
        |`-> (226): nn.Linear(16 -> 16)
        |`-> (227): nn.Linear(16 -> 16)
        |`-> (228): nn.Linear(16 -> 16)
        |`-> (229): nn.Linear(16 -> 16)
        |`-> (230): nn.Linear(16 -> 16)
        |`-> (231): nn.Linear(16 -> 16)
        |`-> (232): nn.Linear(16 -> 16)
        |`-> (233): nn.Linear(16 -> 16)
        |`-> (234): nn.Linear(16 -> 16)
        |`-> (235): nn.Linear(16 -> 16)
        |`-> (236): nn.Linear(16 -> 16)
        |`-> (237): nn.Linear(16 -> 16)
        |`-> (238): nn.Linear(16 -> 16)
        |`-> (239): nn.Linear(16 -> 16)
        |`-> (240): nn.Linear(16 -> 16)
        |`-> (241): nn.Linear(16 -> 16)
        |`-> (242): nn.Linear(16 -> 16)
        |`-> (243): nn.Linear(16 -> 16)
        |`-> (244): nn.Linear(16 -> 16)
        |`-> (245): nn.Linear(16 -> 16)
        |`-> (246): nn.Linear(16 -> 16)
        |`-> (247): nn.Linear(16 -> 16)
        |`-> (248): nn.Linear(16 -> 16)
        |`-> (249): nn.Linear(16 -> 16)
        |`-> (250): nn.Linear(16 -> 16)
        |`-> (251): nn.Linear(16 -> 16)
        |`-> (252): nn.Linear(16 -> 16)
        |`-> (253): nn.Linear(16 -> 16)
        |`-> (254): nn.Linear(16 -> 16)
        |`-> (255): nn.Linear(16 -> 16)
        |`-> (256): nn.Linear(16 -> 16)
        |`-> (257): nn.Linear(16 -> 16)
        |`-> (258): nn.Linear(16 -> 16)
        |`-> (259): nn.Linear(16 -> 16)
        |`-> (260): nn.Linear(16 -> 16)
        |`-> (261): nn.Linear(16 -> 16)
        |`-> (262): nn.Linear(16 -> 16)
        |`-> (263): nn.Linear(16 -> 16)
        |`-> (264): nn.Linear(16 -> 16)
        |`-> (265): nn.Linear(16 -> 16)
        |`-> (266): nn.Linear(16 -> 16)
        |`-> (267): nn.Linear(16 -> 16)
        |`-> (268): nn.Linear(16 -> 16)
        |`-> (269): nn.Linear(16 -> 16)
        |`-> (270): nn.Linear(16 -> 16)
        |`-> (271): nn.Linear(16 -> 16)
        |`-> (272): nn.Linear(16 -> 16)
        |`-> (273): nn.Linear(16 -> 16)
        |`-> (274): nn.Linear(16 -> 16)
        |`-> (275): nn.Linear(16 -> 16)
        |`-> (276): nn.Linear(16 -> 16)
        |`-> (277): nn.Linear(16 -> 16)
        |`-> (278): nn.Linear(16 -> 16)
        |`-> (279): nn.Linear(16 -> 16)
        |`-> (280): nn.Linear(16 -> 16)
        |`-> (281): nn.Linear(16 -> 16)
        |`-> (282): nn.Linear(16 -> 16)
        |`-> (283): nn.Linear(16 -> 16)
        |`-> (284): nn.Linear(16 -> 16)
        |`-> (285): nn.Linear(16 -> 16)
        |`-> (286): nn.Linear(16 -> 16)
        |`-> (287): nn.Linear(16 -> 16)
        |`-> (288): nn.Linear(16 -> 16)
        |`-> (289): nn.Linear(16 -> 16)
        |`-> (290): nn.Linear(16 -> 16)
        |`-> (291): nn.Linear(16 -> 16)
        |`-> (292): nn.Linear(16 -> 16)
        |`-> (293): nn.Linear(16 -> 16)
        |`-> (294): nn.Linear(16 -> 16)
        |`-> (295): nn.Linear(16 -> 16)
        |`-> (296): nn.Linear(16 -> 16)
        |`-> (297): nn.Linear(16 -> 16)
        |`-> (298): nn.Linear(16 -> 16)
        |`-> (299): nn.Linear(16 -> 16)
        |`-> (300): nn.Linear(16 -> 16)
        |`-> (301): nn.Linear(16 -> 16)
        |`-> (302): nn.Linear(16 -> 16)
        |`-> (303): nn.Linear(16 -> 16)
        |`-> (304): nn.Linear(16 -> 16)
        |`-> (305): nn.Linear(16 -> 16)
        |`-> (306): nn.Linear(16 -> 16)
        |`-> (307): nn.Linear(16 -> 16)
        |`-> (308): nn.Linear(16 -> 16)
        |`-> (309): nn.Linear(16 -> 16)
        |`-> (310): nn.Linear(16 -> 16)
        |`-> (311): nn.Linear(16 -> 16)
        |`-> (312): nn.Linear(16 -> 16)
        |`-> (313): nn.Linear(16 -> 16)
        |`-> (314): nn.Linear(16 -> 16)
        |`-> (315): nn.Linear(16 -> 16)
        |`-> (316): nn.Linear(16 -> 16)
        |`-> (317): nn.Linear(16 -> 16)
        |`-> (318): nn.Linear(16 -> 16)
        |`-> (319): nn.Linear(16 -> 16)
        |`-> (320): nn.Linear(16 -> 16)
        |`-> (321): nn.Linear(16 -> 16)
        |`-> (322): nn.Linear(16 -> 16)
        |`-> (323): nn.Linear(16 -> 16)
        |`-> (324): nn.Linear(16 -> 16)
        |`-> (325): nn.Linear(16 -> 16)
        |`-> (326): nn.Linear(16 -> 16)
        |`-> (327): nn.Linear(16 -> 16)
        |`-> (328): nn.Linear(16 -> 16)
        |`-> (329): nn.Linear(16 -> 16)
        |`-> (330): nn.Linear(16 -> 16)
        |`-> (331): nn.Linear(16 -> 16)
        |`-> (332): nn.Linear(16 -> 16)
        |`-> (333): nn.Linear(16 -> 16)
        |`-> (334): nn.Linear(16 -> 16)
        |`-> (335): nn.Linear(16 -> 16)
        |`-> (336): nn.Linear(16 -> 16)
        |`-> (337): nn.Linear(16 -> 16)
        |`-> (338): nn.Linear(16 -> 16)
        |`-> (339): nn.Linear(16 -> 16)
        |`-> (340): nn.Linear(16 -> 16)
        |`-> (341): nn.Linear(16 -> 16)
        |`-> (342): nn.Linear(16 -> 16)
        |`-> (343): nn.Linear(16 -> 16)
        |`-> (344): nn.Linear(16 -> 16)
        |`-> (345): nn.Linear(16 -> 16)
        |`-> (346): nn.Linear(16 -> 16)
        |`-> (347): nn.Linear(16 -> 16)
        |`-> (348): nn.Linear(16 -> 16)
        |`-> (349): nn.Linear(16 -> 16)
        |`-> (350): nn.Linear(16 -> 16)
        |`-> (351): nn.Linear(16 -> 16)
        |`-> (352): nn.Linear(16 -> 16)
        |`-> (353): nn.Linear(16 -> 16)
        |`-> (354): nn.Linear(16 -> 16)
        |`-> (355): nn.Linear(16 -> 16)
        |`-> (356): nn.Linear(16 -> 16)
        |`-> (357): nn.Linear(16 -> 16)
        |`-> (358): nn.Linear(16 -> 16)
        |`-> (359): nn.Linear(16 -> 16)
        |`-> (360): nn.Linear(16 -> 16)
        |`-> (361): nn.Linear(16 -> 16)
        |`-> (362): nn.Linear(16 -> 16)
        |`-> (363): nn.Linear(16 -> 16)
        |`-> (364): nn.Linear(16 -> 16)
        |`-> (365): nn.Linear(16 -> 16)
        |`-> (366): nn.Linear(16 -> 16)
        |`-> (367): nn.Linear(16 -> 16)
        |`-> (368): nn.Linear(16 -> 16)
        |`-> (369): nn.Linear(16 -> 16)
        |`-> (370): nn.Linear(16 -> 16)
        |`-> (371): nn.Linear(16 -> 16)
        |`-> (372): nn.Linear(16 -> 16)
        |`-> (373): nn.Linear(16 -> 16)
        |`-> (374): nn.Linear(16 -> 16)
        |`-> (375): nn.Linear(16 -> 16)
        |`-> (376): nn.Linear(16 -> 16)
        |`-> (377): nn.Linear(16 -> 16)
        |`-> (378): nn.Linear(16 -> 16)
        |`-> (379): nn.Linear(16 -> 16)
        |`-> (380): nn.Linear(16 -> 16)
        |`-> (381): nn.Linear(16 -> 16)
        |`-> (382): nn.Linear(16 -> 16)
        |`-> (383): nn.Linear(16 -> 16)
        |`-> (384): nn.Linear(16 -> 16)
        |`-> (385): nn.Linear(16 -> 16)
        |`-> (386): nn.Linear(16 -> 16)
        |`-> (387): nn.Linear(16 -> 16)
        |`-> (388): nn.Linear(16 -> 16)
        |`-> (389): nn.Linear(16 -> 16)
        |`-> (390): nn.Linear(16 -> 16)
        |`-> (391): nn.Linear(16 -> 16)
        |`-> (392): nn.Linear(16 -> 16)
        |`-> (393): nn.Linear(16 -> 16)
        |`-> (394): nn.Linear(16 -> 16)
        |`-> (395): nn.Linear(16 -> 16)
        |`-> (396): nn.Linear(16 -> 16)
        |`-> (397): nn.Linear(16 -> 16)
        |`-> (398): nn.Linear(16 -> 16)
        |`-> (399): nn.Linear(16 -> 16)
        |`-> (400): nn.Linear(16 -> 16)
        |`-> (401): nn.Linear(16 -> 16)
        |`-> (402): nn.Linear(16 -> 16)
        |`-> (403): nn.Linear(16 -> 16)
        |`-> (404): nn.Linear(16 -> 16)
        |`-> (405): nn.Linear(16 -> 16)
        |`-> (406): nn.Linear(16 -> 16)
        |`-> (407): nn.Linear(16 -> 16)
        |`-> (408): nn.Linear(16 -> 16)
        |`-> (409): nn.Linear(16 -> 16)
        |`-> (410): nn.Linear(16 -> 16)
        |`-> (411): nn.Linear(16 -> 16)
        |`-> (412): nn.Linear(16 -> 16)
        |`-> (413): nn.Linear(16 -> 16)
        |`-> (414): nn.Linear(16 -> 16)
        |`-> (415): nn.Linear(16 -> 16)
        |`-> (416): nn.Linear(16 -> 16)
        |`-> (417): nn.Linear(16 -> 16)
        |`-> (418): nn.Linear(16 -> 16)
        |`-> (419): nn.Linear(16 -> 16)
        |`-> (420): nn.Linear(16 -> 16)
        |`-> (421): nn.Linear(16 -> 16)
        |`-> (422): nn.Linear(16 -> 16)
        |`-> (423): nn.Linear(16 -> 16)
        |`-> (424): nn.Linear(16 -> 16)
        |`-> (425): nn.Linear(16 -> 16)
        |`-> (426): nn.Linear(16 -> 16)
        |`-> (427): nn.Linear(16 -> 16)
        |`-> (428): nn.Linear(16 -> 16)
        |`-> (429): nn.Linear(16 -> 16)
        |`-> (430): nn.Linear(16 -> 16)
        |`-> (431): nn.Linear(16 -> 16)
        |`-> (432): nn.Linear(16 -> 16)
        |`-> (433): nn.Linear(16 -> 16)
        |`-> (434): nn.Linear(16 -> 16)
        |`-> (435): nn.Linear(16 -> 16)
        |`-> (436): nn.Linear(16 -> 16)
        |`-> (437): nn.Linear(16 -> 16)
        |`-> (438): nn.Linear(16 -> 16)
        |`-> (439): nn.Linear(16 -> 16)
        |`-> (440): nn.Linear(16 -> 16)
        |`-> (441): nn.Linear(16 -> 16)
        |`-> (442): nn.Linear(16 -> 16)
        |`-> (443): nn.Linear(16 -> 16)
        |`-> (444): nn.Linear(16 -> 16)
        |`-> (445): nn.Linear(16 -> 16)
        |`-> (446): nn.Linear(16 -> 16)
        |`-> (447): nn.Linear(16 -> 16)
        |`-> (448): nn.Linear(16 -> 16)
        |`-> (449): nn.Linear(16 -> 16)
        |`-> (450): nn.Linear(16 -> 16)
        |`-> (451): nn.Linear(16 -> 16)
        |`-> (452): nn.Linear(16 -> 16)
        |`-> (453): nn.Linear(16 -> 16)
        |`-> (454): nn.Linear(16 -> 16)
        |`-> (455): nn.Linear(16 -> 16)
        |`-> (456): nn.Linear(16 -> 16)
        |`-> (457): nn.Linear(16 -> 16)
        |`-> (458): nn.Linear(16 -> 16)
        |`-> (459): nn.Linear(16 -> 16)
        |`-> (460): nn.Linear(16 -> 16)
        |`-> (461): nn.Linear(16 -> 16)
        |`-> (462): nn.Linear(16 -> 16)
        |`-> (463): nn.Linear(16 -> 16)
        |`-> (464): nn.Linear(16 -> 16)
        |`-> (465): nn.Linear(16 -> 16)
        |`-> (466): nn.Linear(16 -> 16)
        |`-> (467): nn.Linear(16 -> 16)
        |`-> (468): nn.Linear(16 -> 16)
        |`-> (469): nn.Linear(16 -> 16)
        |`-> (470): nn.Linear(16 -> 16)
        |`-> (471): nn.Linear(16 -> 16)
        |`-> (472): nn.Linear(16 -> 16)
        |`-> (473): nn.Linear(16 -> 16)
        |`-> (474): nn.Linear(16 -> 16)
        |`-> (475): nn.Linear(16 -> 16)
        |`-> (476): nn.Linear(16 -> 16)
        |`-> (477): nn.Linear(16 -> 16)
        |`-> (478): nn.Linear(16 -> 16)
        |`-> (479): nn.Linear(16 -> 16)
        |`-> (480): nn.Linear(16 -> 16)
        |`-> (481): nn.Linear(16 -> 16)
        |`-> (482): nn.Linear(16 -> 16)
        |`-> (483): nn.Linear(16 -> 16)
        |`-> (484): nn.Linear(16 -> 16)
        |`-> (485): nn.Linear(16 -> 16)
        |`-> (486): nn.Linear(16 -> 16)
        |`-> (487): nn.Linear(16 -> 16)
        |`-> (488): nn.Linear(16 -> 16)
        |`-> (489): nn.Linear(16 -> 16)
        |`-> (490): nn.Linear(16 -> 16)
        |`-> (491): nn.Linear(16 -> 16)
        |`-> (492): nn.Linear(16 -> 16)
        |`-> (493): nn.Linear(16 -> 16)
        |`-> (494): nn.Linear(16 -> 16)
        |`-> (495): nn.Linear(16 -> 16)
        |`-> (496): nn.Linear(16 -> 16)
        |`-> (497): nn.Linear(16 -> 16)
        |`-> (498): nn.Linear(16 -> 16)
        |`-> (499): nn.Linear(16 -> 16)
        |`-> (500): nn.Linear(16 -> 16)
        |`-> (501): nn.Linear(16 -> 16)
        |`-> (502): nn.Linear(16 -> 16)
        |`-> (503): nn.Linear(16 -> 16)
        |`-> (504): nn.Linear(16 -> 16)
        |`-> (505): nn.Linear(16 -> 16)
        |`-> (506): nn.Linear(16 -> 16)
        |`-> (507): nn.Linear(16 -> 16)
        |`-> (508): nn.Linear(16 -> 16)
        |`-> (509): nn.Linear(16 -> 16)
        |`-> (510): nn.Linear(16 -> 16)
        |`-> (511): nn.Linear(16 -> 16)
         `-> (512): nn.Linear(16 -> 16)
         ... -> output
    }
    (4): nn.JoinTable
  }
  (3): nn.View(512, 4, 4)
  (4): nn.SpatialFullConvolution(512 -> 256, 4x4, 2,2, 1,1)
  (5): nn.SpatialBatchNormalization (4D) (256)
  (6): nn.ReLU
  (7): nn.SpatialFullConvolution(256 -> 128, 4x4, 2,2, 1,1)
  (8): nn.SpatialBatchNormalization (4D) (128)
  (9): nn.ReLU
  (10): nn.SpatialFullConvolution(128 -> 64, 4x4, 2,2, 1,1)
  (11): nn.SpatialBatchNormalization (4D) (64)
  (12): nn.ReLU
  (13): nn.SpatialFullConvolution(64 -> 3, 4x4, 2,2, 1,1)
  (14): nn.Tanh
}
Starting donkey with id: 1 seed: 334
table: 0x39d7abd8
/Users/anthonyyuan/torch/install/bin/luajit: ...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ...earning-master/pixelInterpolation/data/donkey_folder.lua:24: bad argument #2 to 'error' (number expected, got string)
stack traceback:
	[C]: in function 'error'
	...earning-master/pixelInterpolation/data/donkey_folder.lua:24: in main chunk
	[C]: in function 'dofile'
	...-demand-learning-master/pixelInterpolation/data/data.lua:38: in function <...-demand-learning-master/pixelInterpolation/data/data.lua:28>
	[C]: in function 'xpcall'
	...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	...nthonyyuan/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...nthonyyuan/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	...nthonyyuan/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
	...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
	...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
	...-demand-learning-master/pixelInterpolation/data/data.lua:26: in function 'new'
	demo.lua:63: in main chunk
	[C]: in function 'dofile'
	...yuan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x0107bbfbc0

**Comment by pyl62112991** [comment]
how do you solve the problem
