### ISSUE TITLE
Can u tell me how to do my database?

### ISSUE THREAD

**Issue by anthonyyuan** [rhgao/on-demand-learning#3]
Can u tell me how to do my database?

**Comment by rhgao** [comment]
Just download the appropriate dataset and put all the image files in one/several subdirectories. Suppose you put all your images under directory my_directory/images/*.jpg, you should then specify DATA_ROOT=my_directory (not my_directory/images) to train/test the model.

**Comment by rhgao** [comment]
Just download the appropriate dataset and put all the image files in one/several subdirectories. Suppose you put all your images under directory my_directory/images/*.jpg, you should then specify DATA_ROOT=my_directory (not my_directory/images) to train/test the model.
